export const GET_LATEST = 'GET_LATEST'
export const SET_LATEST = 'SET_LATEST'
export const GET_RELEVANT = 'GET_RELEVANT'
export const SET_RELEVANT = 'SET_RELEVANT'
export const GET_SINGLE = 'GET_SINGLE'
export const SET_SINGLE_GAME = 'SET_SINGLE_GAME'
