export { SliderCmp } from './Slider'
export { Slide } from './Slide'
export { Description } from './Description'
export { Rating } from './Rating'
export { Relevant } from './Relevant'
export { Single } from './Single'
export { GameWorld } from './GameWorld'
export { Menu } from './Menu'
export { TopSales } from './TopSales'
export * from './UI'
